// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/8/13 17:48:48
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/个人网站/1-复刻mrkriss/student-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/个人网站/1-复刻mrkriss/student-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/个人网站/1-复刻mrkriss/student-portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/个人网站/1-复刻mrkriss/student-portfolio/plugins/**/*.{js,ts,mjs}","E:/个人网站/1-复刻mrkriss/student-portfolio/composables/**/*.{js,ts,mjs}","E:/个人网站/1-复刻mrkriss/student-portfolio/utils/**/*.{js,ts,mjs}","E:/个人网站/1-复刻mrkriss/student-portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/个人网站/1-复刻mrkriss/student-portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/个人网站/1-复刻mrkriss/student-portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/个人网站/1-复刻mrkriss/student-portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["16"] = "E:/个人网站/1-复刻mrkriss/student-portfolio/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;